# Generated by Django 4.1.5 on 2023-01-08 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_tours', '0003_biketourcard_rename_distance_biketour_distance_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biketour',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='biketour',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='biketour',
            name='id',
        ),
        migrations.RemoveField(
            model_name='biketour',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='biketour',
            name='report',
        ),
        migrations.RemoveField(
            model_name='biketour',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='biketour',
            name='title',
        ),
        migrations.AddField(
            model_name='biketour',
            name='description',
            field=models.CharField(default='no description', max_length=100),
        ),
        migrations.AddField(
            model_name='biketour',
            name='end_date',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='biketour',
            name='name',
            field=models.CharField(default='unnamed', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='biketour',
            name='start_date',
            field=models.DateField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='biketourcard',
            name='bike_tour',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_tours.biketour'),
        ),
        migrations.AlterField(
            model_name='biketourcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='biketourcard',
            name='subtitle',
            field=models.CharField(default='no subtitle', max_length=100),
        ),
        migrations.AlterField(
            model_name='biketourcard',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
        migrations.CreateModel(
            name='BikeTourPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('subtitle', models.CharField(default='no subtitle', max_length=100)),
                ('map_url', models.URLField()),
                ('report', models.CharField(default='no report', max_length=10000)),
                ('bike_tour', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_tours.biketour')),
            ],
        ),
    ]
