# Generated by Django 4.1.5 on 2023-01-08 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_tours', '0004_remove_biketour_card_image_remove_biketour_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketour',
            name='days',
            field=models.IntegerField(verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='biketour',
            name='description',
            field=models.CharField(default='no description', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='biketour',
            name='distance_km',
            field=models.IntegerField(verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='biketour',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='biketour',
            name='name',
            field=models.CharField(default='unnamed', max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='biketour',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
