# Generated by Django 4.1.5 on 2023-01-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_tours', '0006_alter_biketour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketour',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='biketour',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
