# Generated by Django 4.1.5 on 2023-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_tours', '0007_alter_biketour_end_date_alter_biketour_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biketour',
            name='days',
        ),
        migrations.AlterField(
            model_name='biketour',
            name='name',
            field=models.CharField(default='create unique name', max_length=100, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
