# Generated by Django 4.1.5 on 2023-01-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_tours', '0008_remove_biketour_days_alter_biketour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketourcard',
            name='image',
            field=models.ImageField(upload_to='images/bike_tours/card_images'),
        ),
    ]
