# Generated by Django 4.1.5 on 2023-01-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_tours', '0009_alter_biketourcard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biketourpage',
            name='subtitle',
        ),
    ]
