# Generated by Django 4.1.5 on 2023-01-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_tours', '0010_remove_biketourpage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='biketour',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
